version: '3'

services:
  server:
    build: todolist/

    command: ['java', '-jar', '/todolist-backend.jar']

    ports:
      - 8080:8080

  client:
    build: front/

    command: ['npm', 'start']

    network_mode: host

    ports:
      - 3000:3000

    depends_on:
      - server
